---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-server
  name: admin-server-ui
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
    nodePort: 30909
  selector:
    app: admin-server
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-server
  name: admin-server
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: admin-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin-server
  name: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
      labels:
        app: admin-server
    spec:
      containers:
      - image: {{ .Values.adminServer.image }}:{{ .Values.adminServer.tag }}
        name: admin-server
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 15
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 2000m
            memory: 1Gi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        ports:
        - containerPort: 8080
      restartPolicy: Always
status: {}
